{
  "type": "record",
  "name": "MenuItemCreatedV1",
  "namespace": "fd.catalog",
  "fields": [
    {"name":"eventId","type":{"type":"string","logicalType":"uuid"}},
    {"name":"timestamp","type":{"type":"long","logicalType":"timestamp-millis"}},
    {"name":"restaurantId","type":{"type":"string","logicalType":"uuid"}},
    {"name":"menuItemId","type":{"type":"string","logicalType":"uuid"}},
    {"name":"name","type":"string"},
    {"name":"price","type":{"type":"bytes","logicalType":"decimal","precision":19,"scale":2}},
    {"name":"available","type":"boolean"}
  ]
}
